import { GoogleGenAI } from "@google/genai";
import { ModelType, SearchMode, SlideDeck } from '../types';

export const createChatStream = async (
  history: { role: string; parts: { text: string }[] }[],
  message: string,
  model: ModelType,
  searchMode: SearchMode
) => {
  // Initialize inside function to ensure the latest API key is used
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const tools = searchMode === SearchMode.ON ? [{ googleSearch: {} }] : [];
  
  // Create a chat session
  const chat = ai.chats.create({
    model: model,
    history: history.map(h => ({
      role: h.role,
      parts: h.parts
    })),
    config: {
      tools: tools,
      systemInstruction: "You are Skywork AI, a helpful, intelligent, and precise AI assistant. If search tools are enabled, use them to provide up-to-date information. Format your response in clean Markdown. If you use search, the system will handle citation rendering, but you should reference facts clearly.",
    }
  });

  try {
    const resultStream = await chat.sendMessageStream({ message });
    return resultStream;
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const generateSlideImage = async (
  topic: string,
  stylePrompt: string = '',
  referenceImages: string[] = []
): Promise<string> => {
  // Initialize inside function to ensure the latest API key is used
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  // Construct the prompt based on the user's topic and the selected style
  const fullPrompt = `Create a professional presentation slide image about: "${topic}".

  ${stylePrompt}

  The output must be a single, high-quality, professional PPT slide image.`;

  try {
    // Build the parts array: text prompt + reference images (matching BananaPPT logic)
    const parts: any[] = [{ text: fullPrompt }];

    // Add reference images if provided
    if (referenceImages && referenceImages.length > 0) {
      console.log(`Adding ${referenceImages.length} reference images to API request`);
      let totalSize = 0;
      for (const base64Data of referenceImages) {
        totalSize += base64Data.length;
        parts.push({
          inlineData: {
            mimeType: 'image/png',
            data: base64Data
          }
        });
      }
      console.log(`Total base64 data size: ${(totalSize / 1024 / 1024).toFixed(2)} MB`);
    }

    console.log(`Calling Gemini API with ${parts.length} parts (1 text + ${referenceImages.length} images)`);
    console.log('Prompt length:', fullPrompt.length, 'characters');
    console.log('Model:', 'gemini-3-pro-image-preview');
    console.log('API Key present:', !!process.env.API_KEY);

    const requestPayload = {
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: parts
      },
      config: {
        imageConfig: {
          aspectRatio: '16:9',
          imageSize: '1K'
        }
      }
    };

    console.log('Request config:', {
      model: requestPayload.model,
      partsCount: parts.length,
      hasImageConfig: !!requestPayload.config?.imageConfig
    });

    // Use gemini-3-pro-image-preview (Nano Banana Pro)
    const response = await ai.models.generateContent(requestPayload);

    console.log('API response received successfully');
    console.log('Response candidates:', response.candidates?.length);

    // Extract the image from the response
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error: any) {
    console.error("Slide Image Generation Error:", error);
    console.error("Error details:", {
      name: error?.name,
      message: error?.message,
      stack: error?.stack?.split('\n').slice(0, 3),
      response: error?.response,
      status: error?.status,
      statusText: error?.statusText
    });

    // 检查是否是网络错误
    if (error?.message?.includes('fetch')) {
      console.error('Network error detected - possible causes:');
      console.error('1. Request payload too large (current images total MB shown above)');
      console.error('2. API endpoint unreachable or blocked');
      console.error('3. CORS or network connectivity issue');
    }

    throw error;
  }
};