import { GoogleGenAI } from "@google/genai";
import { ModelType, SearchMode, SlideDeck } from '../types';

export const createChatStream = async (
  history: { role: string; parts: { text: string }[] }[],
  message: string,
  model: ModelType,
  searchMode: SearchMode
) => {
  // Initialize inside function to ensure the latest API key is used
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const tools = searchMode === SearchMode.ON ? [{ googleSearch: {} }] : [];
  
  // Create a chat session
  const chat = ai.chats.create({
    model: model,
    history: history.map(h => ({
      role: h.role,
      parts: h.parts
    })),
    config: {
      tools: tools,
      systemInstruction: "You are Skywork AI, a helpful, intelligent, and precise AI assistant. If search tools are enabled, use them to provide up-to-date information. Format your response in clean Markdown. If you use search, the system will handle citation rendering, but you should reference facts clearly.",
    }
  });

  try {
    const resultStream = await chat.sendMessageStream({ message });
    return resultStream;
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const generateSlideImage = async (topic: string, stylePrompt: string = ''): Promise<string> => {
  // Initialize inside function to ensure the latest API key is used
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  // Construct the prompt based on the user's topic and the selected style
  const fullPrompt = `Create a professional presentation slide image about: "${topic}".
  
  ${stylePrompt}
  
  The output must be a single, high-quality, professional PPT slide image.`;

  try {
    // Use gemini-3-pro-image-preview (Nano Banana Pro)
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [
          { text: fullPrompt }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: '16:9',
          imageSize: '1K' 
        }
      }
    });

    // Extract the image from the response
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Slide Image Generation Error:", error);
    throw error;
  }
};